version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
  web:
    build: .
    image: keeganj/bad-bank-docker
    ports:
      - "3000:3000"
    links:
      - mongo
    command: node index.js